[package]
name = "nf_netcat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
block = "0.1.6"
dispatch = "0.2.0"
pico-args = { version = "0.5.0", features = ["combined-flags"] }
